client/components/navbar.js, client/components/pie.js, client/routes.js, package-lock.json, package.json, public/index.html
=> feature: added pie chart component using dummy data

client/components/bar.js, client/components/doughnut.js, client/components/navbar.js, client/routes.js
=> added bar chart component and donught chart component(lol)

client/components/line.js, client/components/navbar.js, client/components/scatterplots.js, client/routes.js
=> feature: line graph and scatter plot

package-lock.json
=> refactor: deleted packagelock

client/components/line.js, client/store/data.js, client/store/index.js, package-lock.json, script/seed.js, server/db/models/userData.js
=> connected thunks to database

client/components/line.js, client/store/data.js
=> adjustments to data flow on front end

client/components/line.js, client/store/data.js
=> feature: combined reducers

client/components/columns.js, client/components/upload.js, client/store/data.js
=> update selected columns and state and parsed data on store state

client/components/upload.js, server/api/charts.js
=> feature: post user data

client/components/line.js, client/store/data.js
=> fixed bug on upload

client/store/data.js, server/api/userDatas.js
=> Get newest data only

client/components/bar.js, client/components/doughnut.js, client/components/pie.js, client/components/scatterplots.js, client/store/data.js
=> feature: graphs connected to backend

client/components/pie.js, client/components/scatterplots.js
=> added more default colors to charts

client/components/bar.js, client/components/line.js, client/components/pie.js, client/components/scatterplots.js
=> Updated graph labels

client/helpers.js/averageAndSum.js
=> Average and sum

client/helpers.js/averageAndSum.js, client/helpers.js/tests/averageAndSum.spec.js
=> fixed small bug

client/helpers.js/tests/averageAndSum.spec.js
=> parseInt on average and sum functions

client/helpers.js/averageAndSum.js, client/helpers.js/tests/averageAndSum.spec.js
=> Cleaning code

client/components/bar.js, client/components/pie.js, client/components/scatterplots.js, client/helpers.js/averageAndSum.js, client/store/data.js
=> feature: columns filtered for better graph view

client/helpers.js/averageAndSum.js
=> added tests

client/app.js, client/components/main.js, client/routes.js, client/store/upload.js, public/style.css
=> file uploaded to redux and fixed layout for charts

client/store/data.js
=> fixed error with helpers.js file

client/components/submit.js
=> bugfix: post request on submit

client/components/submit.js, client/components/test.js, client/components/upload.js, client/store/graph.js, client/store/index.js
=> test: added test code for decision tree

client/components/bar.js, client/components/columns.js, client/components/line.js, client/components/mainComponent.js, client/components/navbar.js, client/components/pie.js, client/routes.js
=> feature: mainComponent created

client/components/bar.js, client/components/line.js, client/components/mainComponent.js, client/components/pie.js, client/components/scatterplots.js, client/components/submit.js, client/components/test.js, client/helpers/numerical.js, client/store/data.js
=> Basic decision tree works

README.md, client/components/navbar.js, client/components/navbar.spec.js, client/helpers/continuous.js, client/store/data.js, client/store/data.spec.js, client/store/graph.js, client/store/graph.spec.js, client/store/upload.spec.js, client/store/user.spec.js, server/api/userDatas.spec.js, server/db/models/userData.spec.js
=> Read me/tests

client/components/mainComponent.js, public/style.css
border-radius: 50%;
font-size: 16px;
padding: 10px;
color: white;
background-color: grey;
---
=> updated style on carousel button 

client/components/columns.js, client/components/main.js, client/components/submit.js, client/components/upload.js, client/store/upload.js, package-lock.json, package.json, public/style.css
=> update: landing page layout

client/components/Profile.js, client/components/bar.js, client/components/line.js, client/components/navbar.js, client/components/pie.js, client/components/save-graph.js, client/components/scatterplots.js, client/components/single-chart.js, client/components/submit.js, client/components/user-home.js, client/routes.js, client/store/index.js, client/store/savedChart.js, server/api/index.js, server/api/savedChart.js, server/db/models/index.js, server/db/models/savedChart.js
=> added user profile and ability to save graphs

client/helpers/averageColumnData.js
=> average Column Data refractored to take in column data instead of arrays

client/components/auth-form.js, client/store/user.js, script/seed.js, server/db/models/user.js
=> updated signup and user to include first and last name

server/db/models/savedChart.js
=> save icons on save graph

client/components/auth-form.js, client/components/submit.js, client/components/upload.js, public/index.html, public/style.css
=> feature: login form css

client/components/Profile.js, client/components/test.js, client/store/graph.spec.js
=> decision tree fleshed out

client/components/bar.js, client/components/line.js, client/components/pie.js, client/components/save-graph.js, client/components/scatterplots.js, client/store/savedChart.js, package-lock.json, package.json, public/style.css
=> updated save graphs

client/components/submit.js, public/style.css
=> fix: merge conflict resolved

client/components/test.js
=> bug fix on decision tree

client/components/bar.js, client/components/line.js, client/components/pie.js, client/components/scatterplots.js, client/components/single-chart.js, client/components/test.js, client/store/savedChart.js, server/db/models/savedChart.js
=> Graphs use titles

script/seed.js
=> added some seed files

client/components/Profile.js, client/components/auth-form.js, client/components/columns.js, client/components/loading.js, client/components/logo.js, client/components/navbar.js, client/components/upload.js, client/routes.js, client/store/user.js, public/style.css
=> update: quick style update

client/components/bar.js, client/components/columns.js, client/components/line.js, client/components/main.js, client/components/mainComponent.js, client/components/outputGraph.js, client/components/pie.js, client/components/saveButtons.js, client/components/scatterplots.js, client/components/submit.js, client/routes.js, public/style.css
=> update: added output graph on the main page

client/components/test.js
=> updated decision tree to take average data when appropriate

client/components/main.js
=> refactor: hide animation with graph

public/style.css
=> refactor: x index animation
